/*
w = wall
m = monster
f = flame thrower gun
b = stair binary
r = stair ram
k = key
e = energy
n = sniper
s = shock trap
= = crush trap
c = collectible item
g = gound
*/

var tileMap = [
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                                                                                         w",
"w                                              wwwwwwww                                                   w",
"w                      wwww                    w      w                  ww                               w",
"w                      w   w                   w      w                  w w                              w",
"w                      w    w                  w      w                  w  w                             w",
"w                      www   w                 w      w                  w   w                            w",
"w                        w   w                 wwwwwwww                  w    w                           w",
"w                        w   w                                           w A  w                           w",
"w                      www   w                                           w L  w                           w",
"w                      w    w                                            w U  w                           w",
"w                      w   w                                             w    w                           w",
"w                      wwww                                              w   w                            w",
"w                                                                        w  w                             w",
"w   wwww                                                                 w w                              w",
"w   w  w                                                                 ww                               w",
"w   wP w                                                                                                  w",
"w   wC w                 wwwwww                                                                           w",
"w   w  w                w      w                                                                          w",
"w   w  w               w        w                                                                         w",
"w   wwww              w          w                                                                        w",
"w                     w          w                                                                        w",
"w    rr               w CONTROL  w                                                                        w",
"w                     w          w                                                                        w",
"w    rr                w        w                                                                         w",
"w                       w      w                                                                          w",
"w    rr                  wwwwww                                                                           w",
"w                                                                                                         w",
"w    rr                                                                                                   w",
"w                                                                                                         w",
"w   wwwww     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                            w",
"w   w   w     w                              w                                                            w",
"w   w R w     w                              w                                                            w",
"w   w E w     w                              w                                                            w",
"w   w G sssssss                              w                                                            w",
"w   w I w     w   sss                        w                                                            w",
"w   w S w     w                              w           cc                                               w",
"w   w T w  ssss        sss                   w           ww                                               w",
"w   w E w     w                              w           cccc                                             w",
"w   w s w  s  w            sss               w           wwww                                             w",
"w   w   w     w                              w           cccccc                                           w",
"w   w   w  ss w                sss           w           wwwwww                                           w",
"w   w   w  ss w                              w           cccccccc                                         w",
"w   w   w     w                              w           wwwwwwww                                         w",
"w   w   w     w                              w           cccccccccc                                       w",
"w   w   wwwwwww                              w           wwwwwwwwww                                       w",
"w   w   w     w                              w                                                            w",
"w   w   w     w                              w           wwwwwwwwwww                                      w",
"w   w   w     w                              w           ccccssccccc                                      w",
"w   w   w     w                              w           wwwwwwwwwww                                      w",
"w   w   w     w                              w           ccccccccccc                                      w",
"w   wwwww     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           wwwwwwwwwww                                      w",
"w                                                        cc==ccccccc                                      w",
"w                                      e                 wwwwwwwwwww                                      w",
"w                                      bb                                    rrrrrrrrrrrrrrrrr            w",
"w                                                                                   =      err            w",
"w                                     m                  wwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrr            w",
"w                                     bb                 wwwwwwwwwww         r                  rr        w",
"w                                 bb                     wwwwwwwwww          r                            w",
"w                                                        wwwwwwwww           r                  rrr       w",
"w                             bb                         wwwwwwww            r                       r    w",
"w                         bb                             wwwwwww             r      ccccccccccccccc    cccw",
"w                     bb                                 wwwwww              r      ccccccccccccccc rr cccw",
"w                                                        wwwww               r      ccccccccccccccc    cccw",
"w        m   m   m  m                                    wwww                r      rrrrrrrrrrrrrrrrrrrrrrw",
"w      bbbbbbbbbbbbbb                k                   www                 r                            w",
"w          cc      bb                bb                  ww                  r   rr                       w",
"w          bb      bb                                                        r      ccc                   w",
"w           ec     bb                                                        r      rrr                   w",
"w           bb     bb                                                        r           rr               w",
"w           cc     bb                                                        r      r                     w",
"w          bbb     bb                                                        r          rrrrr             w",
"w         p    m   bb                                                        r          =====             w",
"w      bbbbbbbbbbbbbb                                                        r      r   rrrrr             w",
"w                                                                            r cc          m              w",
"w   bbbbbb               cc f n cc   m     c  c  c                           rrrrr    rrrrrrr             w",
"w         ccccccccc     bbbbbbbbbbbbbb     b  b  b                                 r                      w",
"w         bbbbbbbbb                                                              r                        w",
"w                                                                    b  b  rrrrr                          w",
"w                   b    bbb                                     b                                        w",
"w                 cc                                         b       b                                    w",
"w                bbb   c                                 b                                                w",
"w                      bbb                                            b                                   w",
"w                           c                        b       m                                            w",
"w                           b                        c                   b                                w",
"w                               ec                   b                                                    w",
"w                              bbbb                    ALU                bb                              w",
"w                                                    bCONTROL  b          cc                              w",
"w                           b                ccc                          bb                    e         w",
"w                   c   w  c c   m   c  c  c         b                                         bb         w",
"w                c  w    bbbbbbbbbb  w  w  w  wwww           m b  b  bb   bb              cc              w",
"w                w       bbbbbbbbbb                  bbbbbbbbbbb                          bb              w",
"w        w    f    n                      w                                                               w",
"w       ww    w   wwww                                                                 bb       cc    cc  w",
"w  c   wwww  mw     =                     w                 m                                   cc    cc  w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
];
