/*
w = wall
m = monster
f = flame thrower gun
b = stair binary
r = stair ram
k = key
e = energy
n = sniper
s = shock trap
= = crush trap
c = collectible item
g = gound
*/

var tileMap = [
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                                                                                         w",
"w                                              wwwwwwww                                                   w",
"w                      wwww                    w      w                  ww                               w",
"w                      w   w                   w      w                  w w                              w",
"w                      w    w                  w      w                  w  w                             w",
"w                      www   w                 w      w                  w   w                            w",
"w                        w   w                 wwwwwwww                  w    w                           w",
"w                        w   w                                           w A  w                           w",
"w                      www   w                                           w L  w                           w",
"w                      w    w                                            w U  w                           w",
"w                      w   w                                             w    w                           w",
"w                      wwww                                              w   w                            w",
"w                                                                        w  w                             w",
"w   wwww                                                                 w w                              w",
"w   w  w                                                                 ww                               w",
"w   wP w                                                                                                  w",
"w   wC w                 wwwwww                                                                           w",
"w   w  w                w      w                                                                          w",
"w   w  w               w        w                                                                         w",
"w   wwww              w          w                                                                        w",
"w                     w          w                                                                        w",
"w    rr               w CONTROL  w                                                                        w",
"w                     w          w                                                                        w",
"w    rr                w        w                                                                         w",
"w                       w      w                                                                          w",
"w    rr                  wwwwww                                                                           w",
"w                                                                                                         w",
"w    rr                                                                                                   w",
"w                                                                                                         w",
"w   wwwww     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                            w",
"w   w   w     w                              w                                                            w",
"w   w R w     w                              w                                                            w",
"w   w E w     w                              w                                                            w",
"w   w G sssssss                              w                                                            w",
"w   w I w     w   sss                        w                                                            w",
"w   w S w     w                              w                                                            w",
"w   w T w  ssss        sss                   w           ww                                               w",
"w   w E w     w                              w           w w                                              w",
"w   w s w  s  w            sss               w           w  w                                             w",
"w   w   w     w                              w           w   w                                            w",
"w   w   w  ss w                sss           w           w    w                                           w",
"w   w   w  ss w                              w           w     w                                          w",
"w   w   w     w                              w           w      w                                         w",
"w   w   w     w                              w           w       w                                        w",
"w   w   wwwwwww                              w           w        w                                       w",
"w   w   w     w                              w           w         w                                      w",
"w   w   w     w                              w           w         w                                      w",
"w   w   w     w                              w           w         w                                      w",
"w   w   w     w                              w           w         w                                      w",
"w   w   w     w                              w           w         w                                      w",
"w   wwwww     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           w ALU     w                                      w",
"w                                                        w         w                                      w",
"w                                                        w         w                                      w",
"w                                                        w         w         rrrrrrrrrrrrrrrrr            w",
"w                                                        w         w                =      err            w",
"w                                                        w         rrrrrrrrrrrrrrrrrrrrrrrrrrr            w",
"w                                                        w         w         r                  rr        w",
"w                                                        w        w          r                            w",
"w                                                        w       w           r                rrrrrr      w",
"w                                                        w      w            r                      rr    w",
"w                                                        w     w             r      ccccccccccccccc    cccw",
"w                                                        w    w              r      ccccccccccccccc rr cccw",
"w                                                        w   w               r      ccccccccccccccc  p cccw",
"w                                                        w  w                r      rrrrrrrrrrrrrrrrrrrrrrw",
"w                                                        w w                 r                            w",
"w                                                        ww                  r   rr                       w",
"w                                                                            r      ccc                   w",
"w                                                                            r      rrr                   w",
"w                                                                            r           rr               w",
"w                                                                            r      r                     w",
"w                                                                            r          rrrrr             w",
"w                                                                            r          =====             w",
"w                                                                            r      r   rrrrr             w",
"w                                                                            r cc          m              w",
"w                 b         f n      m                                       rrrrr    rrrrrrr             w",
"w                       bbbbbbbbbbbbbb                                             r                      w",
"w                bb                                                              r                        w",
"w                                                                    b  b  rrrrr                          w",
"w                   b    bbb                                     b                                        w",
"w                                                            b                                            w",
"w                bbb                                     b                                                w",
"w                      bbb                                                                                w",
"w                                                    b       m                                            w",
"w                           b                        c                                                    w",
"w                                                    b                                                    w",
"w                              bbbb                    ALU                                                w",
"w                                                    bCONTROL  b                                          w",
"w                           b                ccc                                                          w",
"w                   c   w  c c   m   c  c  c         b                                                    w",
"w                c  w    bbbbbbbbbb  w  w  w  wwww           m b                                          w",
"w                w       bbbbbbbbbb                  bbbbbbbbbbb                                          w",
"w        w    f    n                                                                                      w",
"w       ww    w   wwww                                                                                    w",
"w  c   wwww  mw     =                                       m                                             w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
];
